name: docs
on:
  push:
    branches: [main]
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: deploy
  cancel-in-progress: false
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Doxygen, Sphinx, and Breathe
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen python3-sphinx
          pip install breathe sphinx-rtd-theme
        shell: bash
      - name: Setup pages
        id: pages
        uses: actions/configure-pages@v5
      - name: Build docs
        run: |
          cd docs
          mkdir _build
          mkdir _build/doxygen
          doxygen Doxyfile
          make html
          cd ..
      - name: Upload artifact
        if: ${{ !env.ACT }}
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/_build/html
  deploy:
    name: Deploy
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4