name: license_headers

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
jobs:
  check:
    name: Check license headers
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v6
        with:
          go-version: '^1.13.1'
      - run: |
         go install github.com/google/addlicense@latest
         addlicense . -c IBM -l MIT -check