name: lint_clang

permissions:
  contents: read

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
         pip install clang
         ./run-clang-format.py -r include -i && ./run-clang-format.py -r tests/cpp -i