name: lint_black

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Black formatter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
         pip install black
         black . --check